version: '3.8'

services:
  ollama-chat:
    build: .
    ports:
      - "3000:3000"
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - FRONTEND_PORT=3000
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - DEFAULT_MODEL=llama3.2